### ISSUE TITLE
Error Enabling Postgis If Exists

### ISSUE THREAD

**Issue by jgraham87** [mstaack/laravel-postgis#154]
An error occurs tying to enable Postgis via migration.

Copy pasted from docs.

`Call to undefined method MStaack\LaravelPostgis\Schema\Builder::enablePostgisIfNotExists()`

**Comment by gbuckingham89** [comment]
It looks like you're trying to use the new method I introduced in this PR: https://github.com/mstaack/laravel-postgis/pull/152

Do you know what version of the package you have installed? 

It doesn't look like a new version has been tagged (I'm not the package maintainer) since that PR was merged, so if you're looking at the README docs from the `master` branch, they're probably ahead of the version you have installed in your project.

You can use `Schema ::enablePostgis()` in your migrations in earlier versions of the package, but if PostGIS is already enabled in your database, it will likely through an error.

Although it's not recommended (as you may get unexpected updates and breaking changes), you could use `dev-master` as your version constraint for the package in your `composer.json` to get the latest changes (with the new `enablePostgisIfNotExists ()` method). Otherwise, you'll need to wait for a new release to be tagged before using it.

**Comment by jgraham87** [comment]
Thank you very much for the comment. You are correct in the version I am using. I will use the methods you suggest or update my package version. I appreciate your clarification.
