### ISSUE TITLE
Impossible to use on database schema different than 'public'

### ISSUE THREAD

**Issue by grimzy** [mstaack/laravel-postgis#96]
Its currently impossible to use this package with the Postgis extension installed in a schema other than `public` because it is [hardcoded](https://github.com/njbarrett/laravel-postgis/blob/f20044a05d52ba45feb6ae356eb54f65b167e504/src/Eloquent/Builder.php#L27).

For example, in the project I'm currently working on, I create the Postgis extension like this:
```
DB::statement('CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA "' . config('database.connections.pgsql.schema') . '";');
```

Does the schema have to be specified in the query? In my experience, it will use what is in the current database session's `search_path` (which seems to be set by Laravel using the config value: `database.connections.pgsql.schema`).

If the schema **has** to be specified, then I think it should at least look at the Postgres configuration: `config('database.connections.pgsql.schema')` and 
```
protected function asWKT(GeometryInterface $geometry)
{
    return $this->getQuery()->raw(sprintf("public.ST_GeogFromText('%s')", $geometry->toWKT()));
}
```
would become:
```
protected function asWKT(GeometryInterface $geometry)
{
    return $this->getQuery()->raw(sprintf("%s.ST_GeogFromText('%s')", config('database.connections.pgsql.schema'), $geometry->toWKT()));
}
```

What was the goal of: https://github.com/njbarrett/laravel-postgis/pull/70 ? What does it fix?

_PS: Sorry if I created this issue more than once._

**Comment by njbarrett** [comment]
Thank you for submitting this.
PR #70  This was to fix issue #68 

If you have thought of a possible solution, I will gladly accept pull requests to resolve this.

**Comment by grimzy** [comment]
How about this change? Uses the same schema across the application.

Alternatively, I can work on a PR adding a config file where we can define the schema to use with Postgis queries.

**Comment by maurosanjo** [comment]
Hey guys,

I'm currently facing this problem. I have a public schema with postgis installed with a working application. We created a new app in a new schema that will also use postgis. But since I changed laravel default schema, the migrations do not run due to missing types. (ERROR:  type "geography" does not exist at character)

To make it work I had to place:
`DB::statement("SET search_path = newschema, public");`
Before the creation of the table that has a point column.

What would be the best approach for this?
